version: '3'
services:
  postgres:
    container_name: postgres
    build:
      context: ./
      dockerfile: db.Dockerfile
    environment:
      POSTGRES_USER: raezil
      POSTGRES_PASSWORD: droggo1
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: health
    expose:
      - "5432"      
      
    volumes:
      - ./tmp/db:/var/lib/postgresql/data


  redis:
      image: "redis:7-alpine"
      expose:
        - ${REDIS_PORT}
      volumes:
        - ./tmp/redis_data:/var/lib/redis/data

  nginx:
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    expose:
      - "80"
  minio:
    image: minio/minio:latest
    environment:
      MINIO_ROOT_USER: "minioadmin"
      MINIO_ROOT_PASSWORD: "minioadmin"
    volumes:
      - ./data:/data
    ports:
      - 9000:9000
      - 9001:9001
    command: server /data --console-address :9001  # <-- add this
  web:
    build: .
    entrypoint: /opt/app/docker-entrypoint.sh
    command: ["rails", "server", "-b", "0.0.0.0"]
    volumes:
      - .:/opt/app
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - minio
      - redis
    links:
      - postgres
      - minio
      - redis
    env_file:
      - .env

  sidekiq:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/opt/app
      - gem_cache:/usr/local/bundle/gems
      - node_modules:/app/node_modules
    env_file: .env
    environment:
      ENABLE_BOOTSNAP: 'false'
    entrypoint: ./sidekiq-entrypoint.sh


volumes:
  redis:
  gem_cache:
  node_modules: