CREATE USER $POSTGRES_USERNAME WITH PASSWORD $POSTGRES_PASSWORD;
CREATE DATABASE health_development;
GRANT ALL PRIVILEGES ON DATABASE health_development TO $POSTGRES_USERNAME;
CREATE DATABASE health_test;
GRANT ALL PRIVILEGES ON DATABASE health_test TO $POSTGRES_USERNAME;
CREATE DATABASE health_production;
GRANT ALL PRIVILEGES ON DATABASE health_production TO $POSTGRES_USERNAME;