connection: &connection
  adapter: postgresql
  encoding: unicode
  pool: 80
  username: <%= ENV['POSTGRES_USERNAME'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>

development:
  <<: *connection
  database: health_development
  url: <%= ENV['DATABASE_URL'] %>

test:
  <<: *connection
  database: health_test<%= ENV['TEST_ENV_NUMBER'] %>
  url: <%= "#{ENV['DATABASE_URL'].gsub('development', 'test') || ENV['DATABASE_URL'].gsub('production', 'test')}#{ENV.fetch('TEST_ENV_NUMBER')}" %>

production:
  <<: *connection
  database: health_production
  url: <%= ENV['DATABASE_URL'].gsub('development', 'production') %>