connection: &connection
  adapter: postgresql
  encoding: unicode
  pool: 10
  username: <%= ENV['POSTGRES_USERNAME'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>

development:
  <<: *connection
  database: health_development
  url: <%= ENV['DATABASE_URL'] %>

test:
  <<: *connection
  database: health_test
  url: <%= ENV['DATABASE_URL'] %>
production:
  <<: *connection
  database: health_production
  url: <%= ENV['DATABASE_URL'] %>