          <<~GQL
            query {
              retrieveDetailsOfUser {
                  id
                  name
                  gender
                  email
                  phoneNumber
              }
            }
          GQL